# Server configuration
server:
  # Hostname or IP address to bind the proxy server to.
  # "0.0.0.0" binds to all available network interfaces.
  # "127.0.0.1" binds only to the local loopback interface.
  host: "127.0.0.1"

  # Port number for the proxy server to listen on.
  port: 8080

# List of key groups. You need at least one group.
groups:
  - name: "default" # Name for this group of keys (used for potential future features)
    # Target API URL for this group.
    # If omitted, defaults to "https://generativelanguage.googleapis.com".
    # You might change this if Google provides regional endpoints in the future.
    target_url: "https://generativelanguage.googleapis.com"

    # Optional proxy for this group (SOCKS5 with authentication)
    # Format: "socks5://username:password@proxy_host:proxy_port"
    # proxy_url: null # Or "socks5://user:pass@your-proxy.com:1080"

    # List of your Google Gemini API keys for this group.
    # The proxy will rotate through these keys using a round-robin strategy.
    # Add at least one key. Replace the placeholder(s) with your actual keys
    # when creating your `config.yaml`.
    api_keys:
      - "YOUR_GEMINI_API_KEY_1"
      - "YOUR_GEMINI_API_KEY_2"
      # - "YOUR_GEMINI_API_KEY_3" # Add more keys if needed

  # You can add more groups here, each with its own name, target_url, api_keys, and optional proxy_url
  # - name: "another_group"
  #   target_url: "https://another-api.example.com"
  #   # proxy_url: "socks5://user2:pass2@another-proxy.com:1080"
  #   api_keys:
  #     - "ANOTHER_KEY_1"
  #     - "ANOTHER_KEY_2"