# Example configuration for the Gemini Proxy

# Server settings
server:
  # Port the proxy will listen on
  port: 4806
  # Optional: Default top_p value for generation, must be between 0.0 and 1.0.
  # This value will be injected into the request body if it's not already present.
  # top_p: 0.9

  # HTTP client timeout settings (in seconds)
  connect_timeout_secs: 10  # Connection timeout (default: 10, max: 300)
  request_timeout_secs: 60  # Overall request timeout (default: 60, max: 600)

  # Admin panel access token (set to enable admin panel)
  # admin_token: "your-secure-admin-token-here"

  # Security settings
  security:
    require_https: true
    max_login_attempts: 5
    lockout_duration_secs: 3600
    session_timeout_secs: 86400

# Redis connection URL
redis_url: "redis://127.0.0.1:6379"

# API key groups. The proxy will rotate through keys in a round-robin fashion.
groups:
  # Default group. You can have multiple groups.
  - name: "Default"
    # Target upstream URL for this group (required)
    # Must be a valid URL. Example provided uses Google's Generative Language API host.
    target_url: "https://generativelanguage.googleapis.com"
    # List of your Google Gemini API keys
    api_keys:
      - "your-gemini-api-key-1"
      - "your-gemini-api-key-2"
      - "your-gemini-api-key-3"
    # Optional: Define an upstream proxy for this specific group.
    # Supported schemes: http, https, socks5
    # proxy_url: "socks5://user:password@host:port"

  # Example of another group with its own keys and proxy
  # - name: "Group2-With-Proxy"
  #   api_keys:
  #     - "your-other-gemini-key-A"
  #     - "your-other-gemini-key-B"
  #   proxy_url: "http://proxy.example.com:4806"  # Example aligned with default host port

# Number of times to retry a request to the upstream service with the SAME key
# if a retriable server error (5xx) occurs. Defaults to 2.
internal_retries: 2

# Number of minutes to temporarily block a key after it has exhausted all
# internal_retries on a 5xx error. Defaults to 5.
temporary_block_minutes: 5

# Safety multiplier for token calculation to avoid exceeding limits.
# Defaults to 1.2.
# safety_multiplier: 1.2