# Example configuration for the Gemini Proxy

# Server settings
server:
  # Port the proxy will listen on
  port: 8081
  # Optional: Default top_p value for generation, must be between 0.0 and 1.0.
  # This value will be injected into the request body if it's not already present.
  top_p: 0.95
  # Optional: Time-to-live for cached responses in seconds.
  cache_ttl_secs: 300
  # Optional: Maximum number of entries in the cache.
  cache_max_size: 100

# API key groups. The proxy will rotate through keys in a round-robin fashion.
groups:
  # Default group. You can have multiple groups.
  - name: "Default"
    # List of your Google Gemini API keys
    api_keys:
      - "your-gemini-api-key-1"
      - "your-gemini-api-key-2"
      - "your-gemini-api-key-3"
    # Optional: Define an upstream proxy for this specific group.
    # Supported schemes: http, https, socks5
    # proxy_url: "socks5://user:password@host:port"

  # Example of another group with its own keys and proxy
  # - name: "Group2-With-Proxy"
  #   api_keys:
  #     - "your-other-gemini-key-A"
  #     - "your-other-gemini-key-B"
  #   proxy_url: "http://proxy.example.com:8080"