# Server configuration
server:
  # Hostname or IP address to bind the proxy server to.
  host: "127.0.0.1"
  # Port number for the proxy server to listen on.
  port: 8080

# List of key groups
groups:
  - name: "default" # Name for this group of keys
    # Target API URL for this group
    target_url: "https://generativelanguage.googleapis.com"
    # Optional proxy for this group (SOCKS5 with authentication)
    proxy_url: "socks5://fKPj8u:GKcQNr@134.195.154.156:9074"
    # List of API keys for this group
    api_keys:
      - "AIzaSyAz-UsJfx2zu8o3xruBS3YVBpP3yaXgN9k"
      - "AIzaSyDmdz-a412pvo8bSxV0dcg2BKf-c5rgwxU"
      - "AIzaSyAyqDXDgywnd5NoQTALbTrUH_MCp7tse3A"
      - "AIzaSyAgB7U3uG3e3i_EABGC-3ZyIgmigWVvCWQ"
      - "AIzaSyBxpxdNfR_rL1IFi0_cxvPQzK7Cw_StCPg"
      - "AIzaSyD0uA1AtHYqidg47FXnKCmE7Vvm2wsuzLU"
      - "AIzaSyCJWYJZGXhn_KGyO3ldD_BEIbtivOTK8gU"
      - "AIzaSyCzXF6W1bYhL1-6SbWdvrl5v3DFrJ_8qUE"
      - "AIzaSyDAVzQ1e3k96yPeYPVIo8Z3TJI3xmOlINQ"
      - "AIzaSyC2TfSHuJuAinPcA_dy3mlXahlAJ_h-_V8"
      - "AIzaSyA4zX8kBUlNGeshR1Y3TLOQbt05jVygkl4"
      - "AIzaSyCg8RiGjdKYILpR_YbxUK6Yq7i0yRZtAjs"
      # Add more keys here if you have them
  # You can add more groups here, each with its own name, target_url, api_keys, and optional proxy_url
  # - name: "group2"
  #   target_url: "https://another-api.example.com"
  #   # No proxy for this group
  #   # proxy_url: null
  #   api_keys:
  #     - "ANOTHER_KEY_1"
  #     - "ANOTHER_KEY_2"