# Example Configuration for Gemini Proxy

# Optional: A global 'top_p' value to apply to all requests that don't have it specified
# at the client or group level. Must be between 0.0 and 1.0.
# The priority for this setting is: Client Request > Group Config > Global Config.
# top_p: 0.9

# Server configuration where the proxy itself listens.
# The 'host' field is no longer configured here; the server binds to 0.0.0.0 by default.
server:
  # Port number for the proxy server to listen on.
  port: 8080

# List of key groups. The proxy rotates through keys from ALL groups combined.
groups:
  # This group will use the global `top_p` setting (if defined above) ONLY if the
  # client does not provide a `top_p` in their request.
  - name: "default-group"
    # Target URL for requests using keys from this group.
    # If omitted, defaults to the Google API endpoint for OpenAI compatibility.
    # target_url: "https://generativelanguage.googleapis.com"

    # Optional: Specify an upstream proxy (e.g., SOCKS5) for requests.
    # proxy_url: "socks5://user:pass@your-proxy.com:1080"

    # --- API Key Configuration ---
    # --- API Key Configuration ---
    # Option 1 (Recommended): Use Environment Variable
    # The proxy will look for: GEMINI_PROXY_GROUP_DEFAULT_GROUP_API_KEYS
    # See the "API Key Environment Variables" section in README.md for naming rules.
    api_keys: []

    # Option 2 (Less Secure): Define keys directly here
    # api_keys:
    #   - "YOUR_GEMINI_API_KEY_1"
    #   - "YOUR_GEMINI_API_KEY_2"

  # This group overrides the global `top_p` with its own specific value.
  - name: "group-with-override-top-p"
    # Optional: Override the 'top_p' parameter for requests using this group.
    # This value must be between 0.0 and 1.0 (inclusive).
    # It takes precedence over the global `top_p` setting, but is still overridden
    # by a `top_p` value sent in the client's request body.
    top_p: 0.95

    # --- API Key Configuration ---
    # Use environment variable: GEMINI_PROXY_GROUP_GROUP_WITH_OVERRIDE_TOP_P_API_KEYS
    api_keys: []

# You can add more groups as needed.
#
# Example of a third group using a specific proxy and no top_p override:
# - name: "proxied-group"
#   proxy_url: "socks5://user:pass@another-proxy.com:1080"
#   api_keys: [] # Provide keys via GEMINI_PROXY_GROUP_PROXIED_GROUP_API_KEYS