# Example configuration file for Gemini Proxy Key Rotation
# Copy this file to config.yaml and fill in your actual values.

# Server and Log settings
server:
  # Port the proxy will listen on.
  port: 4806
  # Default top_p value for generation. This is injected into the request if not present.
  top_p: 0.7
  # IMPORTANT: Set a strong admin token for admin panel access.
  # Generate one with: openssl rand -hex 32
  admin_token: "your-secure-admin-token-here"
  # Maximum number of tokens allowed in the input request. Requests exceeding this limit will be rejected.
  max_tokens_per_request: 125000
  # HTTP client timeout settings (in seconds).
  connect_timeout_secs: 10
  request_timeout_secs: 60
  # Security settings for the admin panel.
  security:
    require_https: true
    max_login_attempts: 5
    lockout_duration_secs: 3600
    session_timeout_secs: 86400

# Rate limit behavior: BlockUntilMidnight or RetryNextKey
# rate_limit_behavior: retryNextKey

# Redis configuration (optional, for persistent state across restarts).
# Recommended for production deployments.
# redis_url: "redis://127.0.0.1:6379"
# redis_key_prefix: "gemini_proxy:"

# Number of times to retry a request to the upstream service with the SAME key
# if a retriable server error (5xx) occurs. Defaults to 2.
internal_retries: 2

# Number of minutes to temporarily block a key after it has exhausted all
# internal_retries on a 5xx error. Defaults to 5.
temporary_block_minutes: 5

# --- API Key Groups ---
# The proxy will rotate through keys in a round-robin fashion within a group.
groups:
  - name: "default"
    # Target upstream URL for this group.
    target_url: "https://generativelanguage.googleapis.com/v1beta/openai/"
    # List of your Google Gemini API keys.
    api_keys:
      - "YOUR_API_KEY_1_HERE"
      - "YOUR_API_KEY_2_HERE"
      # Add more API keys as needed

  - name: "gemini-alt-17"
    target_url: "https://generativelanguage.googleapis.com/v1beta/openai/"
    api_keys:
      - "YOUR_ALT_API_KEY_1_HERE"
      - "YOUR_ALT_API_KEY_2_HERE"
      # Add more API keys as needed

  - name: "gemini-alt-21"
    target_url: "https://generativelanguage.googleapis.com/v1beta/openai/"
    # Optional: Define an upstream proxy for this specific group.
    # Supported schemes: http, https, socks5
    # proxy_url: "socks5://user:password@host:port"
    api_keys:
      - "YOUR_ALT2_API_KEY_1_HERE"
      - "YOUR_ALT2_API_KEY_2_HERE"
      # Add more API keys as needed
