services:
  gemini-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-proxy-container
    ports:
      - "${GEMINI_PROXY_PORT}:${GEMINI_PROXY_PORT}"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - RUST_BACKTRACE=1
    restart: unless-stopped
    # Ограничения ресурсов для non-swarm режима
    deploy:
      resources:
        limits:
          cpus: '2.0'
    security_opt:
      - seccomp=unconfined