[build]
# Используем базовый набор инструкций x86-64, который поддерживается почти всеми 64-битными процессорами.
# Это может немного снизить производительность, но обеспечит совместимость.
rustflags = ["-C", "target-cpu=x86-64"]